/**
 *
 * $Id$
 */
package dart.validation;

import dart.Constructor;
import dart.Function;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link dart.Class}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ClassValidator {
	boolean validate();

	boolean validateAbstract(boolean value);
	boolean validateExtends(dart.Class value);
	boolean validateImplements(EList<dart.Class> value);
	boolean validateMixins(EList<dart.Class> value);
	boolean validateConstructors(EList<Constructor> value);
	boolean validateMethods(EList<Function> value);
}
