/**
 *
 * $Id$
 */
package dart.validation;

import dart.HTML;
import dart.Stylesheet;

/**
 * A sample validator interface for {@link dart.Component}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ComponentValidator {
	boolean validate();

	boolean validatePublishAs(String value);
	boolean validateStylesheet(Stylesheet value);
	boolean validateTemplate(HTML value);
	boolean validateSelector(String value);
}
