/**
 *
 * $Id$
 */
package dart.validation;

import dart.DartResource;
import dart.Metadata;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link dart.Import}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ImportValidator {
	boolean validate();

	boolean validateDartResource(DartResource value);
	boolean validateAs(String value);
	boolean validateShow(EList<DartResource> value);
	boolean validateHide(EList<DartResource> value);
	boolean validateMetadata(EList<Metadata> value);
}
