/**
 *
 * $Id$
 */
package dart.validation;

import dart.Function;
import dart.Metadata;
import dart.Part;
import dart.Typedef;
import dart.Variable;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link dart.Library}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LibraryValidator {
	boolean validate();

	boolean validateParts(EList<Part> value);
	boolean validateTypedefs(EList<Typedef> value);
	boolean validateMetadata(EList<Metadata> value);
	boolean validateVariables(EList<Variable> value);
	boolean validateFunctions(EList<Function> value);
}
