/**
 *
 * $Id$
 */
package dart.validation;

import dart.AngularType;
import dart.Route;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link dart.Module}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ModuleValidator {
	boolean validate();

	boolean validateTypes(EList<AngularType> value);
	boolean validateRoutes(EList<Route> value);
}
