/**
 *
 * $Id$
 */
package dart.validation;

import dart.HTML;
import dart.Route;

/**
 * A sample validator interface for {@link dart.Route}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RouteValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validatePath(String value);
	boolean validateView(HTML value);
	boolean validateExtends(Route value);
}
